#!/bin/sh
### BEGIN INIT INFO
# Provides:			 niceshaper
# Required-Start:	 $local_fs $network $remote_fs $syslog
# Required-Stop:	 $local_fs $network $remote_fs $syslog
# Default-Start:	 2 3 4 5
# Default-Stop:		 0 1 6
# Short-Description: Dynamic Traffic Shaper
# Description:		 NiceShaper provides dynamic traffic shaping.
### END INIT INFO

# Author: Mariusz Jedwabny <mariusz@jedwabny.net>

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Dynamic traffic shaper"
NAME=niceshaper
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

do_start() {
		start-stop-daemon --start --quiet --pidfile $PIDFILE \
				--exec $DAEMON -- start > /dev/null
}

do_stop() {
		start-stop-daemon --stop --quiet --signal TERM --pidfile $PIDFILE --retry 5 \
				--exec $DAEMON
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
			0) log_end_msg 0 ;;
			1) log_progress_msg "already started"
			   log_end_msg 0 ;;
			*) log_end_msg 1 ;;
		esac
	;;
  stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop
		case "$?" in
				0) log_end_msg 0 ;;
				1) log_progress_msg "already stopped"
				   log_end_msg 0 ;;
				*) log_end_msg 1 ;;
		esac
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
		;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|status}" >&2
	exit 3
	;;
esac

:
